### PR TITLE
Fix incorrect transparent color index for resources

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Fix incorrect transparent color index for resources to ensure future compamility with OXCE.

This warnings below should not appear anymore.

[WARN]	Image Resources/FirestormRestyle/firestorm_base.gif (from SDL) have set incorrect transparent color index 255 instead of 0
[WARN]	Image Resources/FC/FC.gif (from SDL) have set incorrect transparent color index 127 instead of 0
[WARN]	Image Resources/XCL/XCL-FB.gif (from SDL) have set incorrect transparent color index 255 instead of 0
[WARN]	Image Resources/XCL/XCL-NB.gif (from SDL) have set incorrect transparent color index 255 instead of 0
[WARN]	Image Resources/XCL/XCL-TB.gif (from SDL) have set incorrect transparent color index 255 instead of 0
[WARN]	Image Resources/FirestormRestyle/firestorm_minimised.gif (from SDL) have set incorrect transparent color index 127 instead of 0
[WARN]	Image Resources/FirestormRestyle/firestorm_dogfight.gif (from SDL) have set incorrect transparent color index 255 instead of 0
[WARN]	Image Resources/Geoscape/TEXTURE15.GIF (from SDL) have set incorrect transparent color index 255 instead of 0
[WARN]	Image Resources/Geoscape/TEXTURE36.GIF (from SDL) have set incorrect transparent color index 255 instead of 0
[WARN]	Image Resources/Geoscape/TEXTURE57.GIF (from SDL) have set incorrect transparent color index 255 instead of 0

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Don't merge- fixing firestorm tiles. Something went wrong

**Comment by Firestorm01X2** [comment]
Palletes edited again. Now manually without replacing from other tiles. It should work now.

**Comment by Coincident** [comment]
@Firestorm01X2 
You added a new file to the folder "resources/FC". What is the "act.act" file for?

Still testing, but everything seems OK so far.

**Comment by Firestorm01X2** [comment]
AC.act was added by mistake. It is not needed. I will remove it.

**Comment by Firestorm01X2** [comment]
Done

**Comment by Coincident** [comment]
Everything's good, merged!
I will take a look at the rest of the warnings from open-xcom-extended and see if I can fix some more.
After that, I will release a new version with these changes, and include your name in the "credits".

**Pull request merged**
